tcms/core/lib/djangotinymce/tinymce/urls.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.conf.urls.defaults import *

urlpatterns = patterns('tinymce.views',
    url(r'^js/textareas/(?P<name>.+)/$', 'textareas_js', name='tinymce-js'),
    url(r'^js/textareas/(?P<name>.+)/(?P<lang>.*)$', 'textareas_js', name='tinymce-js-lang'),
    url(r'^spellchecker/$', 'spell_check'),
    url(r'^flatpages_link_list/$', 'flatpages_link_list'),
    url(r'^compressor/$', 'compressor', name='tinymce-compressor'),
    url(r'^filebrowser/$', 'filebrowser', name='tinymce-filebrowser'),
    url(r'^preview/(?P<name>.+)/$', 'preview', name='tinymce-preview'),
)

tcms/urls.py
# -*- coding: utf-8 -*-
#
# Nitrate is copyright 2010 Red Hat, Inc.
#
# Nitrate is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version. This program is distributed in
# the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranties of TITLE, NON-INFRINGEMENT,
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# The GPL text is available in the file COPYING that accompanies this
# distribution and at <http://www.gnu.org/licenses>.
#
# Authors:
#   Xuqing Kuang <xkuang@redhat.com>

from django.conf import settings
from django.conf.urls import *
from django.views.generic.base import RedirectView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from tcms.apps.testcases.views import SimpleTestCaseView
from tcms.apps.testcases.views import TestCaseCaseRunDetailPanelView
from tcms.apps.testcases.views import TestCaseCaseRunListPaneView
from tcms.apps.testcases.views import TestCaseReviewPaneView
from tcms.apps.testcases.views import TestCaseSimpleCaseRunView
from tcms.apps.testruns.views import TestRunReportView
from tcms.apps.testruns.views import AddCasesToRunView


# XML RPC handler
from kobo.django.xmlrpc.views import XMLRPCHandlerFactory
xmlrpc_handler = XMLRPCHandlerFactory('TCMS_XML_RPC')

urlpatterns = patterns('',
    # Example:
    # (r'^tcms/', include('tcms.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),

    # Index and static zone
    (r'^$', 'tcms.core.views.index'),
    (r'^search/$', 'tcms.core.views.search'),
    (r'^xmlrpc/$', xmlrpc_handler),

    # Ajax call responder
    (r'^ajax/update/$', 'tcms.core.ajax.update'),
    # TODO: merge this into next mapping
    (r'^ajax/update/case-status$', 'tcms.core.ajax.update_case_status'),
    (r'^ajax/update/cases-case-status/$', 'tcms.core.ajax.update_cases_case_status'),
    (r'^ajax/update/case-run-status$', 'tcms.core.ajax.update_case_run_status'),
    (r'^ajax/update/cases-priority/$', 'tcms.core.ajax.update_cases_priority'),
    (r'^ajax/update/cases-default-tester/$', 'tcms.core.ajax.update_cases_default_tester'),
    (r'^ajax/update/cases-reviewer/$', 'tcms.core.ajax.update_cases_reviewer'),
    (r'^ajax/update/cases-sortkey/$', 'tcms.core.ajax.update_cases_sortkey'),
    (r'^ajax/form/$', 'tcms.core.ajax.form'),
    (r'^ajax/get-prod-relate-obj/$', 'tcms.core.ajax.get_prod_related_obj_json'),
    (r'^management/getinfo/$', 'tcms.core.ajax.info'),
    (r'^management/tags/$', 'tcms.core.ajax.tag'),

    # Attached file zone
    (r'^management/uploadfile/$', 'tcms.core.files.upload_file'),
    (r'^management/checkfile/(?P<file_id>\d+)/$', 'tcms.core.files.check_file'),
    (r'^management/deletefile/(?P<file_id>\d+)/$', 'tcms.core.files.delete_file'),

    (r'^comments/post/', 'tcms.core.contrib.comments.views.post'),
    (r'^comments/list/', 'tcms.core.contrib.comments.views.all'),
    (r'^comments/delete/', 'tcms.core.contrib.comments.views.delete'),

    # Account information zone, such as login method
    (r'^accounts/login/$', 'django.contrib.auth.views.login'),
    (r'^accounts/logout/$', 'tcms.core.contrib.auth.views.logout'),
    (r'^accounts/register/$', 'tcms.core.contrib.auth.views.register'),
    (r'^accounts/confirm/(?P<activation_key>[A-Za-z0-9\-]+)/$', 'tcms.core.contrib.auth.views.confirm'),
    (r'^accounts/changepassword/$', 'django.contrib.auth.views.password_change'),
    (r'^accounts/changepassword/done/$', 'django.contrib.auth.views.password_change_done'),
    (r'^accounts/passwordreset/$', 'django.contrib.auth.views.password_reset'),
    (r'^accounts/passwordreset/done/$', 'django.contrib.auth.views.password_reset_done'),
    (r'^accounts/passwordreset/confirm//(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm'),
    (r'^accounts/profile/$', 'tcms.apps.profiles.views.redirect_to_profile'), # Hacking for default url after login
    (r'^accounts/(?P<username>[\w.@+-]+)/profile/$', 'tcms.apps.profiles.views.profile'),
    (r'^accounts/(?P<username>[\w.@+-]+)/bookmarks/$', 'tcms.apps.profiles.views.bookmark'),
    (r'^accounts/(?P<username>[\w.@+-]+)/recent/$', 'tcms.apps.profiles.views.recent'),

    # Testplans zone
    (r'^plan/new/$', 'tcms.apps.testplans.views.new'),
    (r'^plans/$', 'tcms.apps.testplans.views.all'),
    (r'^plans/ajax/$', 'tcms.apps.testplans.views.ajax_search'),
    (r'^plans/treeview/$', 'tcms.apps.testplans.views.tree_view'),
    (r'^plans/clone/$', 'tcms.apps.testplans.views.clone'),
    (r'^plans/component/$', 'tcms.apps.testplans.views.component'),
    url(r'^plan/(?P<plan_id>\d+)/runs/$', view='tcms.apps.testruns.views.load_runs_of_one_plan',
        name='load_runs_of_one_plan_url'),
    url(r'^plan/(?P<plan_id>\d+)/$', view='tcms.apps.testplans.views.get',
        name='test_plan_url'),
    url(r'^plan/(?P<plan_id>\d+)/(?P<slug>[-\w\d]+)$', view='tcms.apps.testplans.views.get',
        name='test_plan_url'),
    (r'^plan/(?P<plan_id>\d+)/delete/$', 'tcms.apps.testplans.views.delete'),
    (r'^plan/(?P<plan_id>\d+)/chooseruns/$', 'tcms.apps.testplans.views.choose_run'),
    (r'^plan/(?P<plan_id>\d+)/edit/$', 'tcms.apps.testplans.views.edit'),
    (r'^plan/(?P<plan_id>\d+)/attachment/$', 'tcms.apps.testplans.views.attachment'),
    (r'^plan/(?P<plan_id>\d+)/history/$', 'tcms.apps.testplans.views.text_history'),
    (r'^plan/(?P<plan_id>\d+)/cases/$', 'tcms.apps.testplans.views.cases'),

    # Testcases zone
    (r'^case/new/$', 'tcms.apps.testcases.views.new'),
    (r'^cases/$', 'tcms.apps.testcases.views.all'),
    (r'^cases/search/$', 'tcms.apps.testcases.views.search'),
    (r'^cases/load-more/$', 'tcms.apps.testcases.views.load_more_cases'),
    (r'^cases/ajax/$', 'tcms.apps.testcases.views.ajax_search'),
    (r'^cases/automated/$', 'tcms.apps.testcases.views.automated'),
    (r'^cases/tag/$', 'tcms.apps.testcases.views.tag'),
    (r'^cases/component/$', 'tcms.apps.testcases.views.component'),
    (r'^cases/category/$', 'tcms.apps.testcases.views.category'),
    (r'^cases/clone/$', 'tcms.apps.testcases.views.clone'),
    (r'^cases/printable/$', 'tcms.apps.testcases.views.printable'),
    (r'^cases/export/$', 'tcms.apps.testcases.views.export'),
    (r'^case/(?P<case_id>\d+)/$', 'tcms.apps.testcases.views.get'),
    (r'^case/(?P<case_id>\d+)/edit/$', 'tcms.apps.testcases.views.edit'),
    (r'^case/(?P<case_id>\d+)/history/$', 'tcms.apps.testcases.views.text_history'),
    (r'^case/(?P<case_id>\d+)/attachment/$', 'tcms.apps.testcases.views.attachment'),
    (r'^case/(?P<case_id>\d+)/log/$', 'tcms.apps.testcases.views.get_log'),
    (r'^case/(?P<case_id>\d+)/bug/$', 'tcms.apps.testcases.views.bug'),
    (r'^case/(?P<case_id>\d+)/plan/$', 'tcms.apps.testcases.views.plan'),

    url(r'^case/(?P<case_id>\d+)/readonly-pane/$', SimpleTestCaseView.as_view(),
        name='case-readonly-pane'),
    url(r'^case/(?P<case_id>\d+)/review-pane/$', TestCaseReviewPaneView.as_view(),
        name='case-review-pane'),
    url(r'^case/(?P<case_id>\d+)/caserun-list-pane/$', TestCaseCaseRunListPaneView.as_view(),
        name='caserun-list-pane'),
    url(r'^case/(?P<case_id>\d+)/caserun-simple-pane/$', TestCaseSimpleCaseRunView.as_view(),
        name='caserun-simple-pane'),
    url(r'^case/(?P<case_id>\d+)/caserun-detail-pane/$', TestCaseCaseRunDetailPanelView.as_view(),
        name='caserun-detail-pane'),

    # Testruns zone
    (r'^run/new/$', 'tcms.apps.testruns.views.new'),
    (r'^runs/$', 'tcms.apps.testruns.views.all'),
    (r'^runs/ajax/$', 'tcms.apps.testruns.views.ajax_search'),
    (r'^runs/env_value/$', 'tcms.apps.testruns.views.env_value'),
    (r'^runs/clone/$', 'tcms.apps.testruns.views.clone'),
    (r'^run/(?P<run_id>\d+)/$', 'tcms.apps.testruns.views.get'),
    (r'^run/(?P<run_id>\d+)/clone/$','tcms.apps.testruns.views.new_run_with_caseruns'),
    (r'^run/(?P<run_id>\d+)/delete/$', 'tcms.apps.testruns.views.delete'),
    # TODO: Deprecated url
    (r'^run/(?P<run_id>\d+)/execute/$', 'tcms.apps.testruns.views.execute'),
    (r'^run/(?P<run_id>\d+)/edit/$', 'tcms.apps.testruns.views.edit'),
    url(r'^run/(?P<run_id>\d+)/report/$', TestRunReportView.as_view(), name='run-report'),
    (r'^run/(?P<run_id>\d+)/ordercase/$', 'tcms.apps.testruns.views.order_case'),
    (r'^run/(?P<run_id>\d+)/changestatus/$', 'tcms.apps.testruns.views.change_status'),
    (r'^run/(?P<run_id>\d+)/ordercaserun/$', 'tcms.apps.testruns.views.order_case'),
    (r'^run/(?P<run_id>\d+)/removecaserun/$', 'tcms.apps.testruns.views.remove_case_run'),

    url(r'^run/(?P<run_id>\d+)/assigncase/$', AddCasesToRunView.as_view(), name='add-cases-to-run'),

    (r'^run/(?P<run_id>\d+)/cc/$', 'tcms.apps.testruns.views.cc'),
    (r'^run/(?P<run_id>\d+)/update/$', 'tcms.apps.testruns.views.update_case_run_text'),
    (r'^run/(?P<run_id>\d+)/export/$', 'tcms.apps.testruns.views.export'),
    (r'^run/(?P<run_id>\d+)/percent/$', 'tcms.apps.testruns.views.caserun_of_the_status_in_percentage'),

    (r'^caseruns/$', 'tcms.apps.testruns.views.caseruns'),
    (r'^caserun/(?P<case_run_id>\d+)/current/$', 'tcms.apps.testruns.views.set_current'),
    (r'^caserun/(?P<case_run_id>\d+)/bug/$', 'tcms.apps.testruns.views.bug'),
    (r'^caserun/comment-many/', 'tcms.core.ajax.comment_case_runs'),
    (r'^caserun/update-bugs-for-many/', 'tcms.core.ajax.update_bugs_to_caseruns'),

    (r'^linkref/add/$', 'tcms.core.contrib.linkreference.views.add'),
    (r'^linkref/get/$', 'tcms.core.contrib.linkreference.views.get'),

tcms/apps/testreviews/models.py
# -*- coding: utf-8 -*-
#
# Nitrate is copyright 2010 Red Hat, Inc.
#
# Nitrate is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version. This program is distributed in
# the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranties of TITLE, NON-INFRINGEMENT,
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# The GPL text is available in the file COPYING that accompanies this
# distribution and at <http://www.gnu.org/licenses>.
#
# Authors:
#   Xuqing Kuang <xkuang@redhat.com>

from django.db import models
from django.db.models.signals import post_save
from django.core.urlresolvers import reverse

from tcms.apps.testcases.models import TestCaseText, NoneText
from tcms.core.models import TCMSActionModel

from tcms.apps.testreviews import signals as review_watchers


# Create your models here.
class TestReview(TCMSActionModel):
    plan = models.ForeignKey('testplans.TestPlan', related_name='review')
    summary = models.CharField(max_length=255)
    notes = models.TextField(blank=True, null=True)
    author = models.ForeignKey('auth.User', related_name='review_author')
    build = models.ForeignKey('management.TestBuild', related_name='review_build')
    start_date = models.DateTimeField(auto_now_add=True)
    stop_date = models.DateTimeField(blank=True, null=True)

    default_reviewer = models.ManyToManyField(
        'auth.User',
        related_name='review_default_reviewer',
        blank=True,
        null=True,
    )

    env_value = models.ManyToManyField(
        'management.TCMSEnvValue',
        related_name='review_env',
        blank=True,
        null=True,
    )

    class Meta:
        db_table = u'tcms_reviews'

    def add_case(self, case, sort_key = 0):
        self.review_case.create(
            case=case,
            case_text_version=case.latest_text().case_text_version,
            sort_key=sort_key,
        )

    def check_all_review_cases(self, review_case_id = None):
        trvcs = self.review_case.all()
        trvcs = trvcs.select_related('case__case_status')

        if review_case_id:
            for trvc in trvcs:
                if trvc.is_current:
                    trvc.is_current = False
                    trvc.save()

                if trvc.id == review_case_id:
                    trvc.is_current = True
                    trvc.save()

        for trvc in trvcs:
            if not trvc.is_finished():
                return False

        return True

    def get_absolute_url(self, request=None):
        # Upward compatibility code
        if request:
            return request.build_absolute_uri(
                reverse('tcms.apps.testreviews.views.get', args=[self.pk, ])
            )

        return self.get_url(request)

    def get_url_path(self):
        return reverse('tcms.apps.testreviews.views.get', args=[self.pk, ])

    def mail(self, template, subject, context, request=None):
        from tcms.core.utils.mailto import mailto

        to = [self.author.email]
        for dr in self.default_reviewer.all():
            to.append(dr.email)

        mailto(template, subject, to, context, request)

class TestReviewCase(TCMSActionModel):
    review = models.ForeignKey(TestReview, related_name='review_case')
    case = models.ForeignKey('testcases.TestCase', related_name='review_case')
    reviewer = models.ForeignKey(
        'auth.User',
        related_name='review_case_reviewer',
        blank=True,
        null=True
    )
    case_text_version = models.IntegerField()
    running_date = models.DateTimeField(auto_now_add=True)
    close_date = models.DateTimeField(null = True, blank=True)
    is_current = models.BooleanField(default=False)
    sort_key = models.IntegerField(default=0)

    class Meta:
        db_table = u'tcms_review_cases'

    def get_text_with_version(self, case_text_version=None):
        if case_text_version:
            try:
                return TestCaseText.objects.get(
                    case__case_id=self.case_id,
                    case_text_version=case_text_version
                )
            except TestCaseText.DoesNotExist, error:
                return NoneText
        try:
            return TestCaseText.objects.get(
                case__case_id=self.case_id,
                case_text_version=self.case_text_version
            )
        except TestCaseText.DoesNotExist:
            return NoneText

    def is_finished(self):
        if self.case.case_status.name == 'PROPOSED':
            return False

        return True


# Signals handler
post_save.connect(review_watchers.post_review_saved, sender=TestReview)

tcms/core/contrib/comments/models.py
# -*- coding: utf-8 -*-
# 
# Nitrate is copyright 2010 Red Hat, Inc.
# 
# Nitrate is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version. This program is distributed in
# the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranties of TITLE, NON-INFRINGEMENT,
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# 
# The GPL text is available in the file COPYING that accompanies this
# distribution and at <http://www.gnu.org/licenses>.

tcms/core/lib/djangotinymce/tinymce/models.py
# Copyright (c) 2008 Joost Cassee
# Licensed under the terms of the MIT License (see LICENSE.txt)

from django.db import models
from django.contrib.admin import widgets as admin_widgets
from tinymce import widgets as tinymce_widgets

class HTMLField(models.TextField):
    """
    A large string field for HTML content. It uses the TinyMCE widget in
    forms.
    """
    def formfield(self, **kwargs):
        defaults = {'widget': tinymce_widgets.TinyMCE}
        defaults.update(kwargs)

        # As an ugly hack, we override the admin widget
        if defaults['widget'] == admin_widgets.AdminTextareaWidget:
            defaults['widget'] = tinymce_widgets.AdminTinyMCE

        return super(HTMLField, self).formfield(**defaults)

tcms/apps/management/forms.py
# -*- coding: utf-8 -*-
#
# Nitrate is copyright 2010 Red Hat, Inc.
#
# Nitrate is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version. This program is distributed in
# the hope that it will be useful, but WITHOUT ANY WARRANTY; without
# even the implied warranties of TITLE, NON-INFRINGEMENT,
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# The GPL text is available in the file COPYING that accompanies this
# distribution and at <http://www.gnu.org/licenses>.
#
# Authors:
#   Yuguang Wang <yuwang@redhat.com>

from django import forms
from tcms.apps.management.models import Version

class VersionForm(forms.ModelForm):

    class Meta:
        model = Version

tcms/templates/plan/get_attachments.html
<div class="mixbar">
	<span class="tit">Add attachment</span>
	{% if perms.management.add_testattachment %}
	<a href="{% url "tcms.apps.testplans.views.attachment" test_plan.plan_id %}" class="addlink">add</a>
	{% endif %}
</div>
<table class="list" cellspacing="0" cellspan="0" width="100%">
	<thead>
		<tr>
			<th align="left">File name</th>
			<th align="left" width="10%">Submitter</th>
			<th align="left" width="20%">Create date</th>
			<th align="left" width="20%">Mimetype</th>
			<th align="left" width="10%">Action</th>
		</tr>
	</thead>
	<tbody>
		{% for attachment in test_plan.attachment.all %}
		<tr id="{{ attachment.attachment_id }}" class="{% cycle 'odd' 'even' %}">
			<td><a href="{% url "tcms.core.files.check_file" attachment.attachment_id %}">{{ attachment.file_name }}</a></td>
			<td>{{ attachment.submitter }}</td>
			<td>{{ attachment.create_date }}</td>
			<td>{{ attachment.mime_type }}</td>
			<td><a href="{% url "tcms.core.files.check_file" attachment.attachment_id %}">View</a> | <a onclick="deleConfirm({{attachment.attachment_id}},'from_plan',{{test_plan.plan_id}})" href="#">Delete</a></td>
		</tr>
		{% empty %}
		<tr><td colspan="5" align="center"><span class="grey">No attachments</span></td></tr>
		{% endfor %}
	</tbody>
</table>

tcms/templates/plan/get_reviews.html
<table class="list" id="testreview_table"  cellpadding="0" cellspacing="0" border="0">
	<thead>
		<tr>
			<th align="left" class="number widthID">#</th>
			<th align="left" class="text">Test Review Summary</th>
			<th align="left" width="100" class="text" >Author</th>
			<th align="left" width="150" class="date-iso" >Start date</th>
			<th align="left" width="50" class="number">Cases</th>
		</tr>
	</thead>
	<tbody>
		{% for test_review in test_reviews %}
		<tr class="{% cycle 'odd' 'even' %}">	
			<td valign="top">
				<a href="{% url "tcms.apps.testreviews.views.get" test_review.id %}">{{ test_review.id }}</a>
			</td>
			<td valign="top" class="subject">
				<a href="{% url "tcms.apps.testreviews.views.get" test_review.id %}">{{ test_review.summary }} review summary</a>
			</td>
			<td valign="top"><a href="{% url "tcms.apps.profiles.views.profile" test_review.author.username %}">{{ test_review.author }}</a></td>
			<td valign="top">{{ test_review.start_date }}</td>
			<td valign="top" align="center">{{ test_review.total_num_review_cases }}</td>
		</tr>
		{% empty %}
		<tr>
			<td colspan="5">
				{% if perms.testreviews.add_testreview %}
				<span class="prompt-message"><center>No Test Review was found in this plan, if you  want to create one ,please select proposed cases to <b>Create Test Review</b>.</span>
				<br/>
				<span class="system_help">
					Notice that :Only proposed test case could be used in test review.
				</span>
				{% else %}
				<span class="prompt-message"><center >No Test Review was found in this plan.</center></span>
				{% endif %}
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

tcms/templates/plan/new.html
{% extends "tcms_base.html" %}

{% block subtitle %}Create new test plan{% endblock %}

{% block custom_stylesheet %}
{% endblock %}

{% block custom_javascript %}
<script type="text/javascript" src='{{ STATIC_URL }}js/lib/tinymce/jscripts/tiny_mce/tiny_mce.js'></script>
<script type="text/javascript" src="{{ STATIC_URL }}js/testplan_actions.js"></script>
<script type="text/javascript" src="{{ STATIC_URL }}admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript">
Nitrate.Utils.after_page_load(Nitrate.TestPlans.Create.on_load);
</script>
{% endblock %}

{% block contents %}

<div id="content">
	<div class="sprites crumble">
		<a href="{% url "tcms.core.views.index" %}">Home</a>
		>> <a href="{% url "tcms.apps.testplans.views.all" %}">Planning</a>
		>> New Test Plan
	</div>
	<form method="post" action="{% url "tcms.apps.testplans.views.new" %}" enctype="multipart/form-data">
		<h2>Create New Test Plan</h2>
		<div class="Detailform border-1" >
			<table class="editor" cellspan="0" cellspacing="0">
				<tr>
					<td width="20%" valign="top"><label class="lab strong" for="id_title">Plan Name</label><span >{{ form.attrib.errors }}</span></td>
					<td width="80%">
						<span class="name summary">{{ form.name }}</span>
						<div >{{ form.name.errors }}</div>
					</td>
				</tr>
				<tr>
					<td width="20%" valign="top"><label class="lab strong" for="id_product_id">Product</label></td>
					<td>
						<span class="name" >{{ form.product }}</span>
						<span >{{ form.product.errors }}</span>
                        <a id="add_id_product" href="{{ ADMIN_PREFIX }}/management/product/add/" class="addlink" onclick="return popupAddAnotherWindow(this);">
							Add Product
						</a>
						<span class="grey">After Add and Refresh page</span>
                        
					</td>
				</tr>
				<tr>
					<td width="20%" valign="top"><label class="lab strong" for="id_version_id">Product Version</label></td>
					<td>
						<span>{{ form.default_product_version }}</span>
						<span >{{ form.default_product_version.errors }}</span>
                        <a id="add_id_default_product_version" href="{{ ADMIN_PREFIX }}/management/version/add/" class="addlink" onclick="return popupAddAnotherWindow(this, 'product');">
							Add Product Version
						</a>
						<span class="grey">After Add and Refresh page</span>
					</td>
				</tr>
				<tr>
					<td valign="top"><label class="lab strong" for="id_type_id">Type</label></td>
					<td >
						<span class="name"> {{ form.type }} </span>
						<div > {{ form.type.errors }} </div>
					</td>
				</tr>
				<tr>
					<td valign="top"><label class="lab" for="id_parent">Parent ID</label></td>
					<td >
						<span class="name">{{ form.parent }}</span>
						<div>{{ form.parent.errors }}</div>
					</td>
				</tr>
				<tr>
					<td valign="top"><label class="lab" for="id_summary">Plan Document: </label></td>
					<td>
						<div class="mec">{{ form.text }}</div>
						<div >{{ form.text.errors }}</div>
						<span>Or upload a plan document</span>
						{{ form.upload_plan_text }}
						<span class="grey">Html, Plain text or ODT is acceptable.</span> 
						<div >{{ form.upload_plan_text.errors }}</div>
					</td>
				</tr>
				<tr>
					<td valign="top"><label class="lab" for="id_env_group_id">Environment Group</label></td>
					<td colspan="3">
						<span class="name">{{ form.env_group }}{{ form.env_group.errors }}</span>
						<span>
							<a class="system_help" href="#" title="" id="env_group_help_link">What is environment group?</a>
							<div id="env_group_help" class="system_info" style="display:none">
								<p>
									Environment Group represent group of environment properties and all values of these properties. <br/>
									TCMS uses environment variables to define the test hardware setup. The Environment Group is the top level container object, it contains one or more Properties, each having a range of values. Properties can belong to more than one group.
									<br/>
									Then when creating test run , you can set one value of each property under this environment group as environment of run testing.
									<br/>
									<a href="http://riddler.bne.redhat.com/TCMS-User_Guide/index.html#User_Guide-Environments">More Information</a>
									<a href="#" class="right-action" title="close the tip" id="env_group_help_close">Close</a>
								</p>

							</div>
						</span>
					</td>
				</tr>
				<tr>
					<td valign="top"><label class="lab" for="id_extra_link">Reference Link:</label></td>
					<td>
						<div class="name summary">{{ form.extra_link }}</div>
						<div >{{ form.extra_link.errors }}</div>
					</td>
				</tr>
			</table>
			<div class="submit-row" >
				<input type="submit" value="Create test plan" />
				<input type="button" value="Cancel" onclick="history.back()"/>
			</div>
		</div> 
	</form>
</div>
{% endblock %}